package org.hcl.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2018-03-29T10:42:53.671+08:00
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebServiceClient(name = "PaymentEJBService", 
                  wsdlLocation = "http://localhost:8080/webservices/PaymentEJB?wsdl",
                  targetNamespace = "http://org.hcl") 
public class PaymentEJBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.hcl", "PaymentEJBService");
    public final static QName PaymentEJBPort = new QName("http://org.hcl", "PaymentEJBPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webservices/PaymentEJB?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentEJBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webservices/PaymentEJB?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentEJBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentEJBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentEJBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentEJBService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentEJBService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentEJBService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PaymentEJB
     */
    @WebEndpoint(name = "PaymentEJBPort")
    public PaymentEJB getPaymentEJBPort() {
        return super.getPort(PaymentEJBPort, PaymentEJB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentEJB
     */
    @WebEndpoint(name = "PaymentEJBPort")
    public PaymentEJB getPaymentEJBPort(WebServiceFeature... features) {
        return super.getPort(PaymentEJBPort, PaymentEJB.class, features);
    }

}
