package org.hcl.ejb;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2018-03-29T10:42:53.349+08:00
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebService(targetNamespace = "http://org.hcl", name = "PaymentEJB")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentEJB {

    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://org.hcl", className = "org.hcl.ejb.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://org.hcl", className = "org.hcl.ejb.TestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String test();
}
